#! /bin/sh

case "$1" in
    start)
        cd /var/lib/bookbag/sync
        /usr/bin/twistd --python syncd.py --pidfile /var/run/syncd.pid
        ;;
    stop)
        kill `cat /var/run/syncd.pid`
        ;;
    restart)
        kill `cat /var/run/syncd.pid`
        cd /var/lib/bookbag/sync
        /usr/bin/twistd --python syncd.py --pidfile /var/run/syncd.pid
        ;;
    *)
        echo "Usage: syncd.sh {start|stop|restart}"
        exit 1
        ;;
esac

