redis:
  image: redis
  ports:
    - "6379:6379"
    - "9022:22"

apollo:
  image: apollo
  environment:
    JAVA_HOME: /usr/lib/jvm/jre-1.6.0
  ports:
    - "61713:61613"
    - "61714:61614"
    - "61723:61623"
    - "61724:61624"
    - "61781:61681"
  volumes:
    - apollo/etc:/var/lib/mybroker/etc
    - apollo/log:/var/lib/mybroker/log
  command: /var/lib/mybroker/bin/apollo-broker run
  
db:
  image: mysql
  ports:
    - "3306:3306"
    - "8026:22"
  volumes:
    - /home/wzhao/site_dbs/mysql:/var/lib/mysql
    
web:
  image: ketao/web
  ports:
    - "423:443"
    - "80:80"
    - "8025:22"
  volumes:
    - ./www/etc:/etc/httpd/conf
    - ./www/log:/var/log/httpd
    - ./www/courseware_doc:/mnt/courseware_doc
    - ./www/www:/var/www
    - /home/wzhao/ds:/root/ds
  links:
    - redis
    - db
    - apollo

daemon:
  image: pydaemon
  ports:
    - "8027:22"
  volumes:
    - www/www/cloudedu/bin:var/lib/ketao
  links:
    - apollo
    - db
  command: /var/lib/ketao/pydaemon