#! /bin/sh

export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python
export WORKON_HOME=/var/lib/virtualenvs
. /usr/local/bin/virtualenvwrapper.sh
workon yuhua

case "$1" in
    start)
        cd /var/www/yuhua/bookbag/sync
        /var/lib/virtualenvs/yuhua/bin/twistd --python syncd.py --pidfile /var/run/syncd.pid
        ;;
    stop)
        kill `cat /var/run/syncd.pid`
        ;;
    restart)
        kill `cat /var/run/syncd.pid`
        cd /var/www/yuhua/bookbag/sync
        /var/lib/virtualenvs/yuhua/bin/twistd --python syncd.py --pidfile /var/run/syncd.pid
        ;;
    *)
        echo "Usage: syncd.sh {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
